### ISSUE TITLE
Where are the flies?

### ISSUE THREAD

**Issue by jvalle** [fponticelli/flymaze#2]
When I loaded up the game 'flymaze', I was really hoping to see some flies... instead I only saw maze.  And a face-less snake.  Also there are no explosions or droplet technologies.  Please advise

**Comment by fponticelli** [comment]
Be patient my affectionate fan, the flies are coming and they will bring joy and pain. The facelessness has been addressed in #1. I cannot make any promise on explosions or droplets.

**Comment by fponticelli** [comment]
Dear Coder, I hope you will appreciate the addition of droplets, flies and eatings of the same. Still missing explosions but I am not sure where to make them happen. In the meanwhile please enjoy: https://rawgit.com/fponticelli/flymaze/master/bin/index.html

Closing since the explosions are out of the scope of this issue.

**Comment by jvalle** [comment]
:+1:
